version: '3.3'

networks:
  sdk-js:
    internal: true
  outside:
    external: true

services:
  web:
     container_name: sdk-js-${CI_JOB_ID}_web
     image: ${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
     build:
       context: .
       dockerfile: bin/docker/images/sdk-js/Dockerfile
     networks:
       sdk-js:
       outside:
         aliases:
           - ${DOCKER_SERVICE}-${CI_JOB_ID}-web
