version: '3.3'

networks:
  traefik_traefik:
    external: true
  sdk-js:
    internal: true
  outside-pi-overlay:
    external: true

services:
  web:
      image: ${REGISTRY_URL}/${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
      build:
       context: .
       dockerfile: bin/docker/images/sdk-js/Dockerfile
      deploy:
          labels:
            - "traefik.frontend.rule=Host:${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.hipay-pos-platform.com"
            - "traefik.port=80"
            - "traefik.docker.network=traefik_traefik"
          placement:
            constraints:
              - node.hostname == docker
          replicas: 1
          update_config:
            parallelism: 2
            delay: 30s
          restart_policy:
            condition: on-failure
      networks:
        traefik_traefik:
        sdk-js:
        outside-pi-overlay:
          aliases:
            - ${DOCKER_SERVICE}-${CI_JOB_ID}-web

